### ISSUE TITLE
 freqtrade download-data -t 5m 15m 1h 4h 1d --days 500

### ISSUE THREAD

**Issue by bjwie** [ntsd/freqtrade-configs#1]
Hi Ntsd,

just a small hint you can use:
freqtrade download-data -t 5m 15m 1h 4h 1d --days 500

for timeframe in '5m' '15m' '1h' '4h' '1d'; do
     freqtrade download-data --exchange binance -t $timeframe --days 500
done

best regards

**Comment by ntsd** [comment]
I see, Thanks for the tip. I tired `-t 5m,15m,1h,4h,1d` but it didn't work lol.

**Comment by bjwie** [comment]
without comma
freqtrade download-data -t 5m 15m 1h 4h 1d --days 500 <=== Correct
freqtrade download-data -t 5m, 15m, 1h, 4h, 1d --days 500 <=== Wrong
